spring:
  application:
    name: taco-cloud
  thymeleaf:
    cache: false

  datasource:
    generate-unique-name: false
    name: taco-cloud-db

  data:
    mongodb:
      host: localhost
      port: 27017
      database: taco_cloud_db