spring:
  application:
    name: taco-cloud
  thymeleaf:
    cache: false

  datasource:
    generate-unique-name: false
    name: taco-cloud-db

  cassandra:
    keyspace-name: taco_cloud
    schema-action: recreate
    local-datacenter: datacenter1